# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: varint.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='varint.proto',
  package='',
  serialized_pb='\n\x0cvarint.proto\"\x15\n\x06VarInt\x12\x0b\n\x03int\x18\x01 \x02(\x05')




_VARINT = _descriptor.Descriptor(
  name='VarInt',
  full_name='VarInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int', full_name='VarInt.int', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=37,
)

DESCRIPTOR.message_types_by_name['VarInt'] = _VARINT

class VarInt(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARINT

  # @@protoc_insertion_point(class_scope:VarInt)


# @@protoc_insertion_point(module_scope)
